### ISSUE TITLE
Indicate journal frequency with dct:accrualPriodicity & controlled values

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#59]
I just learned that there are controlled values in ZDB data for frequency information. I will investigate this so that we can also add this to the RDF.

**Comment by acka47** [comment]
In the DINI KIM context it was proposed to use  `dcterms:accrualPeriodicity` and values from http://marc21rdf.info/terms/continuingfrequency#<MARC-Code>. http://marc21rdf.info/ is currently down, though...

**Comment by acka47** [comment]
The source field probably is 406. From the [MAB documentation](http://www.dnb.de/SharedDocs/Downloads/DE/DNB/standardisierung/mabTitelBibliographischeDaten2001.txt?__blob=publicationFile):

```

406       NORMIERTER ERSCHEINUNGSVERLAUF

          Indikator:
          blank = nicht spezifiziert
          a     = abgeschlossenes Erscheinen
          b     = fortlaufendes Erscheinen

          Unterfelder:
          Beginngruppe:
          $5    = Parallele Zaehlung
          $f    = Sachliche Benennung
          $d    = Bandzaehlung
          $e    = Heft
          $b    = Tag
          $c    = Monat
          $j    = Berichtszeit bzw. Erscheinungszeit
          $h    = Abweichende Erscheinungszeit
          $g    = Kommentar zur Beginngruppe

          Endegruppe:
          $n    = Bandzaehlung
          $o    = Heft
          $l    = Tag
          $m    = Monat
          $k    = Berichtszeit bzw. Erscheinungszeit
          $i    = Abweichende Erscheinungszeit
          $q    = Kommentar zur Endegruppe
```

**Comment by acka47** [comment]
http://marc21rdf.info/ is up again. Here is the controlled value list for frequency of continuing resources in turtle:

```
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix : <http://www.w3.org/2004/02/skos/core#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix dc: <http://purl.org/dc/elements/1.1/> .
@prefix reg: <http://metadataregistry.org/uri/schema/registry/> .

<http://marc21rdf.info/terms/continuingfre#>
    dc:title "MARC21-008: Frequency of continuing resource" ;
    a :ConceptScheme .

<http://marc21rdf.info/terms/continuingfre#%23>
    reg:identifier <http://marc21rdf.info/terms/3853> ;
    reg:status <http://metadataregistry.org/uri/RegStatus/1001> ;
    a :Concept ;
    :inScheme <http://marc21rdf.info/terms/continuingfre#> ;
    :notation "#"@en ;
    :prefLabel "no determinable frequency"@en .

<http://marc21rdf.info/terms/continuingfre#a>
    reg:identifier <http://marc21rdf.info/terms/3854> ;
    reg:status <http://metadataregistry.org/uri/RegStatus/1001> ;
    a :Concept ;
    :definition "Once a year."@en ;
    :inScheme <http://marc21rdf.info/terms/continuingfre#> ;
    :notation "a"@en ;
    :prefLabel "annual"@en .

<http://marc21rdf.info/terms/continuingfre#b>
    reg:identifier <http://marc21rdf.info/terms/3855> ;
    reg:status <http://metadataregistry.org/uri/RegStatus/1001> ;
    a :Concept ;
    :definition "Every two months."@en ;
    :inScheme <http://marc21rdf.info/terms/continuingfre#> ;
    :notation "b"@en ;
    :prefLabel "bimonthly"@en ;
    :scopeNote "Includes 6, 7, or 8 times a year."@en .

<http://marc21rdf.info/terms/continuingfre#c>
    reg:identifier <http://marc21rdf.info/terms/3856> ;
    reg:status <http://metadataregistry.org/uri/RegStatus/1001> ;
    a :Concept ;
    :definition "Twice a week."@en ;
    :inScheme <http://marc21rdf.info/terms/continuingfre#> ;
    :notation "c"@en ;
    :prefLabel "semiweekly"@en .

<http://marc21rdf.info/terms/continuingfre#d>
    reg:identifier <http://marc21rdf.info/terms/3857> ;
    reg:status <http://metadataregistry.org/uri/RegStatus/1001> ;
    a :Concept ;
    :definition "Once a day."@en ;
    :inScheme <http://marc21rdf.info/terms/continuingfre#> ;
    :notation "d"@en ;
    :prefLabel "daily"@en ;
    :scopeNote "Includes Saturday and Sunday."@en .

<http://marc21rdf.info/terms/continuingfre#e>
    reg:identifier <http://marc21rdf.info/terms/3858> ;
    reg:status <http://metadataregistry.org/uri/RegStatus/1001> ;
    a :Concept ;
    :definition "Every two weeks."@en ;
    :inScheme <http://marc21rdf.info/terms/continuingfre#> ;
    :notation "e"@en ;
    :prefLabel "biweekly"@en .

<http://marc21rdf.info/terms/continuingfre#f>
    reg:identifier <http://marc21rdf.info/terms/3859> ;
    reg:status <http://metadataregistry.org/uri/RegStatus/1001> ;
    a :Concept ;
    :definition "Twice a year."@en ;
    :inScheme <http://marc21rdf.info/terms/continuingfre#> ;
    :notation "f"@en ;
    :prefLabel "semiannual"@en .

<http://marc21rdf.info/terms/continuingfre#g>
    reg:identifier <http://marc21rdf.info/terms/3860> ;
    reg:status <http://metadataregistry.org/uri/RegStatus/1001> ;
    a :Concept ;
    :definition "Every two years."@en ;
    :inScheme <http://marc21rdf.info/terms/continuingfre#> ;
    :notation "g"@en ;
    :prefLabel "biennial"@en .

<http://marc21rdf.info/terms/continuingfre#h>
    reg:identifier <http://marc21rdf.info/terms/3861> ;
    reg:status <http://metadataregistry.org/uri/RegStatus/1001> ;
    a :Concept ;
    :definition "Every three years."@en ;
    :inScheme <http://marc21rdf.info/terms/continuingfre#> ;
    :notation "h"@en ;
    :prefLabel "triennial"@en .

<http://marc21rdf.info/terms/continuingfre#i>
    reg:identifier <http://marc21rdf.info/terms/3862> ;
    reg:status <http://metadataregistry.org/uri/RegStatus/1001> ;
    a :Concept ;
    :inScheme <http://marc21rdf.info/terms/continuingfre#> ;
    :notation "i"@en ;
    :prefLabel "three times a week"@en .

<http://marc21rdf.info/terms/continuingfre#j>
    reg:identifier <http://marc21rdf.info/terms/3863> ;
    reg:status <http://metadataregistry.org/uri/RegStatus/1001> ;
    a :Concept ;
    :inScheme <http://marc21rdf.info/terms/continuingfre#> ;
    :notation "j"@en ;
    :prefLabel "three times a month"@en .

<http://marc21rdf.info/terms/continuingfre#k>
    reg:identifier <http://marc21rdf.info/terms/3864> ;
    reg:status <http://metadataregistry.org/uri/RegStatus/1001> ;
    a :Concept ;
    :definition "More frequent than daily."@en ;
    :inScheme <http://marc21rdf.info/terms/continuingfre#> ;
    :notation "k"@en ;
    :prefLabel "continuously updated"@en .

<http://marc21rdf.info/terms/continuingfre#m>
    reg:identifier <http://marc21rdf.info/terms/3865> ;
    reg:status <http://metadataregistry.org/uri/RegStatus/1001> ;
    a :Concept ;
    :inScheme <http://marc21rdf.info/terms/continuingfre#> ;
    :notation "m"@en ;
    :prefLabel "monthly"@en ;
    :scopeNote "Includes 9, 10, 11, or 12 times a year."@en .

<http://marc21rdf.info/terms/continuingfre#q>
    reg:identifier <http://marc21rdf.info/terms/3866> ;
    reg:status <http://metadataregistry.org/uri/RegStatus/1001> ;
    a :Concept ;
    :definition "Every three months."@en ;
    :inScheme <http://marc21rdf.info/terms/continuingfre#> ;
    :notation "q"@en ;
    :prefLabel "quarterly"@en ;
    :scopeNote "Includes 4 times a  year."@en .

<http://marc21rdf.info/terms/continuingfre#s>
    reg:identifier <http://marc21rdf.info/terms/3867> ;
    reg:status <http://metadataregistry.org/uri/RegStatus/1001> ;
    a :Concept ;
    :definition "Twice a month."@en ;
    :inScheme <http://marc21rdf.info/terms/continuingfre#> ;
    :notation "s"@en ;
    :prefLabel "semimonthly"@en .

<http://marc21rdf.info/terms/continuingfre#t>
    reg:identifier <http://marc21rdf.info/terms/3868> ;
    reg:status <http://metadataregistry.org/uri/RegStatus/1001> ;
    a :Concept ;
    :inScheme <http://marc21rdf.info/terms/continuingfre#> ;
    :notation "t"@en ;
    :prefLabel "three times a year"@en .

<http://marc21rdf.info/terms/continuingfre#u>
    reg:identifier <http://marc21rdf.info/terms/3869> ;
    reg:status <http://metadataregistry.org/uri/RegStatus/1001> ;
    a :Concept ;
    :inScheme <http://marc21rdf.info/terms/continuingfre#> ;
    :notation "u"@en ;
    :prefLabel "unknown"@en .

<http://marc21rdf.info/terms/continuingfre#w>
    reg:identifier <http://marc21rdf.info/terms/3870> ;
    reg:status <http://metadataregistry.org/uri/RegStatus/1001> ;
    a :Concept ;
    :definition "Once a week."@en ;
    :inScheme <http://marc21rdf.info/terms/continuingfre#> ;
    :notation "w"@en ;
    :prefLabel "weekly"@en .

<http://marc21rdf.info/terms/continuingfre#z>
    reg:identifier <http://marc21rdf.info/terms/3871> ;
    reg:status <http://metadataregistry.org/uri/RegStatus/1001> ;
    a :Concept ;
    :definition "Frequency other than annual, bimonthly, semiweekly, daily, biweekly, semiannual, biennial, triennial, three times a week, three times a month, continuously updated, monthly, quarterly, semimonthly, three times a year, weekly."@en ;
    :inScheme <http://marc21rdf.info/terms/continuingfre#> ;
    :notation "z"@en ;
    :prefLabel "other"@en .

<http://metadataregistry.org/uri/RegStatus/1001>
    a :Concept ;
    :prefLabel "Published"@en .
```

**Comment by acka47** [comment]
> The source field probably is 406

No, it's not. In the ZDB it is Pica+ field `018@.a`, see the [documentation](http://www.zeitschriftendatenbank.de/fileadmin/user_upload/ZDB/pdf/zdbformat/1800.pdf) which also includes the code list:

```
d täglich
t drei- bis fünfmal wöchentlich
c zweimal wöchentlich
w wöchentlich
e vierzehntäglich
s halbmonatlich
m monatlich
b alle zwei Monate
q vierteljährlich
f halbjährlich
a jährlich
i dreimal im Jahr
j dreimal im Monat
g alle zwei Jahre
h alle drei Jahre
z unregelmässig 
```

ZDB also implements the RDF approach we would like to implement, e.g. `018@	$aw` becomes `dcterms:accrualPeriodicity <http://marc21rdf.info/terms/continuingfre%23w>` in RDF ([example](http://ld.zdb-services.de/data/204679-9.ttl)).

I can not find the controlled values in hbz Aleph export data, though, see for example http://lobid.org/hbz01/HT001387709. (I can neither find the information in the DNB MARC XML, see e.g. http://d-nb.info/011172355/about/marcxml where it should be in fields 853-855, subfield w.)

If I am right and the information is not part of the hbz data, we won't be able to implement this.

**Comment by acka47** [comment]
I found it in 052, 8-10. From the [MAB documentation]()

```
051     VEROEFFENTLICHUNGSSPEZIFISCHE ANGABEN ZU BEGRENZTEN
        WERKEN

...

         8-10  Erscheinungsweise
               d = taeglich
               t = drei- bis fuenfmal woechentlich
               c = zweimal woechentlich
               w = woechentlich
               e = vierzehntaegig
               s = halbmonatlich
               m = monatlich
               b = alle zwei Monate
               q = vierteljaehrlich
               f = halbjaehrlich
               a = jaehrlich
               g = alle zwei Jahre
               h = alle drei Jahre
               z = unregelmaessig oder sonstige Erscheinungsweise
```

Regarding the matichng, the abbreviations are the same except for Mab `t` ("drei- bis fuenfmal woechentlich") which has no direct match in the MARC codes i suggest using MARC `i` ("three times a week") instead as it is a very close match:

d -> http://marc21rdf.info/terms/continuingfre#d
t -> http://marc21rdf.info/terms/continuingfre#i
c -> http://marc21rdf.info/terms/continuingfre#c
w -> http://marc21rdf.info/terms/continuingfre#w
e -> http://marc21rdf.info/terms/continuingfre#e
s -> http://marc21rdf.info/terms/continuingfre#s
m -> http://marc21rdf.info/terms/continuingfre#m
b -> http://marc21rdf.info/terms/continuingfre#b
q -> http://marc21rdf.info/terms/continuingfre#q
f -> http://marc21rdf.info/terms/continuingfre#f
a -> http://marc21rdf.info/terms/continuingfre#a
g -> http://marc21rdf.info/terms/continuingfre#g
h -> http://marc21rdf.info/terms/continuingfre#h
z -> http://marc21rdf.info/terms/continuingfre#z

**Comment by acka47** [comment]
We could also use [bf:frequency](http://id.loc.gov/ontologies/bibframe/frequency) as property.

**Comment by ChristophEwertowski** [comment]
I second the use of bibframe frequency. We aren't limited to a specific set of controlled values with that.

**Comment by dr0i** [comment]
Not sure about the `labels.json` entry - we already have a `frequency`. Is this good: 
 
    "label": "Erscheinungfrequenz",
    "name": "publicationFrequency"` ?

? Here the complete entries:

    {
        "uri": "http://rdaregistry.info/Elements/u/P60538",
        "label": "Erscheinungsweise",
        "name": "frequency",
        "referenceType": "String",
        "container": "@set",
        "multilangLabel": { }
    },
    {
        "uri": "http://id.loc.gov/ontologies/bibframe/frequency",
        "label": "Erscheinungfrequenz",
        "name": "publicationFrequency",
        "referenceType": "String",
        "container": "@set",
        "multilangLabel": { }
    },

**Comment by ChristophEwertowski** [comment]
+1 without the *Erscheinungsfrequenz* wrongly spelled (missing s). For non-libriarians the term is more explicit than *Erscheinungsweise*.

**Comment by dr0i** [comment]
Thx @ChristophEwertowski fixed the typo.
Another question is:
should this new property be better subsumed under the `publication`-object? What then with the `secondaryPublication`? (Maybe better leave it at is is directly clinging under the root object).

**Comment by ChristophEwertowski** [comment]
On the one hand it belongs to the publication, on the other hand it's easier to reference under the root object. Is the secondaryPublication attached to the publication? I couldn't find it with a search. 
Also I get a 404 if I look up the context url for [secondaryPublication](http://purl.org/lobid/lv#secondaryPublication).

**Comment by acka47** [comment]
> Also I get a 404 if I look up the context url for [secondaryPublication](http://purl.org/lobid/lv#secondaryPublication). 

No 404 here. But the property is missing in the vocab, see also https://github.com/lobid/vocabs/issues/53.

**Comment by fsteeg** [comment]
As discussed yesterday, this should also show up in the UI.

**Comment by fsteeg** [comment]
We just discussed this offline, here's a suggestion to group the publication data:

```
publication : [
  {
    type: PublicationEvent,
    frequency: {...}, 
    ...
  },
  {
    type: DigitizationEvent, 
    ...
  },
]
```

That is, instead of having `publication`, `secondaryPublication` and `publicationFrequency` on the top level, everything is nested under the `publication` key.

**Comment by acka47** [comment]
+1 for @fsteeg's proposal – with one reservation: We should not call the type "DigitizationEvent" or similar. This is basically information about the "Sekundärform" (sometimes calles "Sekundärausgabe") which in some cases will be microfiche or other. In English, although terms like "surrogate" or "reproduction" seem to also be in use, you can also find the term "secondary form". So I think we are fine with using "SecondaryPublication" as type. We will have to add it to lobid vocab. Will adjust https://github.com/lobid/vocabs/issues/53 accordingly.

**Comment by acka47** [comment]
> This is basically information about the "Sekundärform" (sometimes calles "Sekundärausgabe") which in some cases will be microfiche or other. 

This query for secondary publication from 1975 to 1990 shows that most of them are microforms: http://lobid.org/resources/search?q=secondaryPublication.startDate%3A1975-1990&size=100

**Comment by acka47** [comment]
Thinking about this I am not sure whether we actually need "SecondaryPublication" at all. Why not simply also use schema:PublicationEvent for this? That we are dealing with a publication of a secondary form becomes clear by the fact that the date is later in time than for the primary PublicationEvent...

**Comment by acka47** [comment]
Just discussed this via chat with @ChristophEwertowski.  As it might be useful to query for secondary forms, we should somehow mark the secondary publications as such. Thus, we will add the type but make it `SecondaryPublicationEvent`. (We already have `OfficialPublication` in the vocab which is a type of resource.) I will open a separate issue for all the changes.

**Comment by acka47** [comment]
This is done, isn't it? @ChristophEwertowski, please close the issue if you also think so.

**Comment by acka47** [comment]
As I just wanted to open another issue regarding publication frequency, we can leave this open and put it here.

139724 entries don't have a specific frequency specified at all but only `http://marc21rdf.info/terms/continuingfre#` as ID (which is the namespace of the controlled vocabulary), see http://lobid.org/resources/search?q=publication.frequency.label:terms&format=json.

I think, the problem is that the implementation in the morph starts counting the indicator a `1` and not at `0`. Will submit a PR.

**Comment by acka47** [comment]
It's probably better when @ChristophEwertowski so that there are no problems with branches & merging.

**Comment by ChristophEwertowski** [comment]
Problem solved on data side, see http://test.lobid.org/resources/search?q=publication.frequency.label:terms&format=json or [example resource (test)](http://test.lobid.org/resources/HT017028573?format=json) / [example resource (production)](http://lobid.org/resources/HT017028573?format=json). I suppose that it is not shown in the frontend because the webpage is still cached (the labels.json has the URL in it). Right @fsteeg or @dr0i ?

**Comment by acka47** [comment]
The problem I noted in https://github.com/hbz/lobid-resources/issues/59#issuecomment-289398895 and via chat is still existent.

Take for example HT015427971 ([source](http://lobid.org/hbz01/HT015427971), [test](http://test.lobid.org/resources/HT015427971?format=json)). 052 looks like this: 

```xml
<controlfield tag="052">p||||||tz||||||</controlfield>
```

In position 0, we have a `p`. Positions 1-6 are empty. Position 7 has the `t`, and at `8` we have `z`. As the frequency is taken from positions 8 to 10, the frequency indicator is `z` which means "unregelmaessig oder sonstige Erscheinungsweise" = http://marc21rdf.info/terms/continuingfre#z. This corresponds with the publication note which says "Periodizität: 3x jährl., bis 2009: 2x jährl.". Currently, the value is taken from position 7, i.e. `t` which results in the – incorrect – frequency "drei- bis fünfmal wöchentlich", see the data on test.

Systematically, a lot of entries are wrong as position 7 is taken where you find the values that could all be in position 8. From the [MAB documentation](http://www.dnb.de/SharedDocs/Downloads/DE/DNB/standardisierung/mab2FormatSatzkennungSegment000Nov2001.txt?__blob=publicationFile):

```
 7  Publikationsstatus
               a = fortlaufende Publikation ohne geplanten
                   Abschluss
               f = Titelaenderung
               t = eingestelltes Erscheinen
               z = keine Angabe moeglich
```

That is why we have so much http://marc21rdf.info/terms/continuingfre#i in the data as `t` seems to be the most used value in 052, position 7.

As a consequence, we have to add a period at each `|` part in https://github.com/hbz/lobid-resources/blob/747f81ae8ab1e19afa0fe7829b24e4486c4a3022/src/main/resources/morph-hbz01-to-lobid.xml#L697 to get the correct values.

**Comment by ChristophEwertowski** [comment]
The last commit should fix it: [Example (production)](http://lobid.org/resources/HT017028573?format=json) / [example (test)](http://test.lobid.org/resources/HT017028573?format=json).

**Comment by ChristophEwertowski** [comment]
An issue was opened for the wrongly shown frequency ids (https://github.com/hbz/lobid-resources/issues/362).

**Comment by acka47** [comment]
This is still not correct. The example file now has the wrong frequency = http://marc21rdf.info/terms/continuingfre#i ("dreimal wöchentlich"), although the MAB source has a `d` = at 052, position 8 (and also `publication.note` says "Periodizität: tägl."):

```xml
<controlfield tag="052">z||||||td||||||</controlfield>
``` 

@ChristophEwertowski, I suggest you just do what I already said twice (via chat and in https://github.com/hbz/lobid-resources/issues/59#issuecomment-290033313):

> we have to add a period at each `|` part in https://github.com/hbz/lobid-resources/blob/747f81ae8ab1e19afa0fe7829b24e4486c4a3022/src/main/resources/morph-hbz01-to-lobid.xml#L697 to get the correct values.

**Comment by acka47** [comment]
I just pushed a fix to the branch. Please review.

**Comment by ChristophEwertowski** [comment]
+1
