### ISSUE TITLE
MabXmlClobs with erroneous holdings

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#952]
There are some MabXmlClobs with holdings that should not be there, e.g.  http://lobid.org/hbz01/HT000173606. In Aleph this seems to be indicated by the "CAT" field where this atavism remains to be noted. 
See email-thread "Stand lobid versus hbz-Verbunddatenbank".

Snippet from the source:

```xml
<datafield tag="088" ind1=" " ind2=" ">
  <subfield code="a">290</subfield>
</datafield>
```

**Comment by dr0i** [comment]
Now this came to attention to customers. This should be fixed, really.

**Comment by acka47** [comment]
I.N. reports a problem that (probably) has the same source:

Am 14.11.19 um 15:29 schrieb I.N.:
> Wenn man die Titelaufnahme (https://nwbib.de/HT020282074) aufruft, 
> erscheint rechts eine Karte mit Bestandsangaben („Bestand in 3 
> Bibliotheken“), wie bei einer Druckausgabe.
> 
> In der ZDB (ID 2999768-9) und in der HBZ-Titeldatei gibt es aber keine 
> Bestandsangaben. Daher die Frage: Woher kommen in lobid die 
> Bestandsangaben zu den drei Bibliotheken im Feld „hasItem“?
> 
> Warum sind es genau diese drei Bibliotheken und nicht z.B. der OPAC der 
> ULB Münster, über den man die Titelaufnahme auch aufrufen könnte?
> 
> Eigentlich hatte ich erwartet, dass rechts oben der Link zur Website 
> angezeigt wird, wie z.B. bei der Online-Zeitschrift „Concilium medii 
> aevi“  (https://nwbib.de/HT012984988)?

**Comment by acka47** [comment]
The upstream problem wasn't fixed but it seems we do not create a holding entry (`hasItem`) anymore if only a sigel but no other information exists in `088`. All the source examples from above at least can not be found in the JSON-LD anymore. I could not find the commit/PR where we fixed this, though but I guess we can close this one. What do you think, @dr0i ?

**Comment by dr0i** [comment]
@acka47 hm, I can see all three Isils `{ "A 96", "829", "743"}` in lobid.org/resources/HT020282074.json. At least they are not shown in the map of holding organisations (https://nwbib.de/HT020282074). 
For http://lobid.org/resources/HT000173606.json you are right, the "dangling item" is not in the data.
Why the latter has changed I cannot say. Must be a change in the data, because the morph hasn't changed, supposedly. The morph wants to say " don't create a itemid if a signature is missing"  but obviously this fails. This should be fixed, as we obviously don't get a fix in the data.

**Comment by dr0i** [comment]
As discussed offline with @acka47 it's sufficient to not show this data.
The data cannot be filtered by just take items _with_ signatures into account, because there may be totly valid items lacking signature.
That leaves it to a problem in the original db ("upstream").

**Comment by TobiasNx** [comment]
I am closing this ticket, since it is a problem with the MAB data. which we do not use anymore
